from CNNClassifier.components.stage_01_data_ingestion import DataIngestion 
from CNNClassifier.components.stage_02_prepare_basemodel import PrepareBaseModel
from CNNClassifier.components.stage_03_train import Training
from CNNClassifier.components.stage_04_evaluate import Evaluation